[package]
name = "proto2arrow"
version = "0.1.0"
authors = ["Harsha Jujjavarapu <jujjavarapu94@gmail.com>"]
edition = "2024"
description = "Attribute Macro that generates Arrow Builders from Protos"
keywords = ["macros", "protos", "protobuf", "arrow"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/sriharshaj/proto2arrow"
include = [
    "/Cargo.toml",
    "../README.md",
    "/src/**"
]
readme = "../README.md"

[lib]
proc-macro = true

[dependencies]
heck = "0.5.0"
quote = "1.0.40"
syn = { version = "2.0.106", features = ["full", "extra-traits"] }
