// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct User {
    #[prost(uint32, tag = "1")]
    pub id: u32,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub email: ::prost::alloc::string::String,
    #[prost(uint32, tag = "4")]
    pub age: u32,
    #[prost(bool, tag = "5")]
    pub is_active: bool,
    #[prost(enumeration = "user::UserType", tag = "6")]
    pub r#type: i32,
    #[prost(message, optional, tag = "7")]
    pub address: ::core::option::Option<user::Address>,
    #[prost(message, repeated, tag = "10")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
    #[prost(map = "int32, message", tag = "11")]
    pub posts: ::std::collections::HashMap<i32, Post>,
    #[prost(enumeration = "PostType", repeated, tag = "12")]
    pub post_types: ::prost::alloc::vec::Vec<i32>,
    #[prost(map = "string, enumeration(PostType)", tag = "13")]
    pub user_string: ::std::collections::HashMap<::prost::alloc::string::String, i32>,
    #[prost(map = "int32, message", tag = "14")]
    pub bank: ::std::collections::HashMap<i32, BankAccount>,
    #[prost(oneof = "user::PaymentMethod", tags = "8, 9")]
    pub payment_method: ::core::option::Option<user::PaymentMethod>,
}
/// Nested message and enum types in `User`.
pub mod user {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Address {
        #[prost(string, tag = "1")]
        pub street: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub city: ::prost::alloc::string::String,
        #[prost(string, tag = "3")]
        pub state: ::prost::alloc::string::String,
        #[prost(string, tag = "4")]
        pub zip_code: ::prost::alloc::string::String,
        #[prost(string, tag = "5")]
        pub country: ::prost::alloc::string::String,
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum UserType {
        Reader = 0,
        Author = 1,
        Editor = 2,
    }
    impl UserType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Reader => "READER",
                Self::Author => "AUTHOR",
                Self::Editor => "EDITOR",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "READER" => Some(Self::Reader),
                "AUTHOR" => Some(Self::Author),
                "EDITOR" => Some(Self::Editor),
                _ => None,
            }
        }
    }
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum PaymentMethod {
        #[prost(message, tag = "8")]
        CreditCard(super::CreditCard),
        #[prost(message, tag = "9")]
        BankAccount(super::BankAccount),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Post {
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub body: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(float, tag = "1")]
    pub amount: f32,
    #[prost(uint64, tag = "2")]
    pub timestamp: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreditCard {
    #[prost(string, tag = "1")]
    pub card_number: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub expiry_month: u32,
    #[prost(uint32, tag = "4")]
    pub expiry_year: u32,
    #[prost(string, tag = "5")]
    pub cvv: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BankAccount {
    #[prost(string, tag = "1")]
    pub account_number: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub routing_number: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub bank_name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PostType {
    Science = 0,
    Arts = 1,
    Politics = 3,
}
impl PostType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Science => "SCIENCE",
            Self::Arts => "ARTS",
            Self::Politics => "POLITICS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SCIENCE" => Some(Self::Science),
            "ARTS" => Some(Self::Arts),
            "POLITICS" => Some(Self::Politics),
            _ => None,
        }
    }
}
